Create usergroups and add users to them automatically
rimmington/disquick pull request #3
Opened 2016-11-15 04:24 UTC by dwillie

2016-11-16 03:43 UTC, rimmington requested changes

2016-11-16 03:43 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/groupadd -f ${group}\n") user.groups))}
I'm not sure it's a good idea to create groups by default; the user might intend to run the service under an existing system group. Instead, add a `userGroups` attr to `user` and create only those.

2016-11-16 03:43 UTC, rimmington commented on pkgs/mkService.nix
> +      # Create user home
I think `# Setup user` covers these, and in a lot of cases these comments will be followed by empty space.

2016-11-16 03:43 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/usermod -a -G ${group} ${user.name}\n") user.groups))}
This isn't necessary; `chpst` (used to switch user) doesn't look at the groups a user is in.

2016-11-16 03:43 UTC, rimmington commented on pkgs/mkService.nix
> +
:frowning_face:

2016-11-16 04:08 UTC, dwillie commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/groupadd -f ${group}\n") user.groups))}
So groups for system groups and userGroups for the groups we're creating ourselves?

2016-11-16 04:10 UTC, dwillie commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/usermod -a -G ${group} ${user.name}\n") user.groups))}
If the user isn't a member of the group, how do we use it for restricting filesystem access?

2016-11-16 04:13 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/groupadd -f ${group}\n") user.groups))}
Yes.

2016-11-16 04:16 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/usermod -a -G ${group} ${user.name}\n") user.groups))}
The group will be one of the executable's [supplementary group ids](http://unix.stackexchange.com/a/18290).

2016-11-16 05:01 UTC, dwillie commented
@rimmington I think that addresses what you want, is it sane? Seems to work. Also, did you want me to use commit tags?

2016-11-16 05:28 UTC, rimmington requested changes
I think this is the correct approach. I guess it'd be good to use commit tags, but I'm not really fussed.

Please also update `doc/mkService.md` with the new `userGroups` arg.

2016-11-16 05:28 UTC, rimmington commented on pkgs/mkService.nix
> +
:frowning_face:

2016-11-16 05:28 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatStrings (map (group: "${remoteShadow}/bin/groupadd -f ${group}\n") user.userGroups))}
`lib.concatStrings (map f l)` ≡ `lib.concatMapStrings f l`

2016-11-16 05:28 UTC, rimmington commented on pkgs/mkService.nix
> +          allGroups = (builtins.concatLists [ user.groups user.userGroups ]);
`builtins.concatLists [ as bs ]` ≡ `as ++ bs`

2016-11-16 05:28 UTC, rimmington commented on pkgs/mkService.nix
> +          suf = lib.optionalString (allGroups != []) ":${lib.concatStringsSep ":" allGroups}";
`lib.optionalString (l != []) ":${lib.concatStringsSep ":" l}"` ≡ `lib.concatMapStrings (i: ":${i}") l`

(This one is my fault.)

2016-11-16 23:33 UTC, rimmington requested changes

2016-11-16 23:33 UTC, rimmington commented on pkgs/mkService.nix
> +      ${(lib.concatMapStrings (group: "${remoteShadow}/bin/groupadd -f ${group}\n") user.userGroups)}
`{()}`

2016-11-16 23:33 UTC, rimmington commented on pkgs/mkService.nix
> +          suf = lib.concatMapStrings (g: ":${g}:") allGroups;
No trailing `:`.

2016-11-17 00:22 UTC, rimmington commented
@dwillie Changes look good. Do you want to squash those commits?

2016-11-17 03:26 UTC, rimmington commented
![](http://i.imgur.com/XRE6BsV.gif)

2016-11-17 03:26 UTC, merged